-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyBfrHkfRPBhHLiZe
x7uQSr5lnKlJIz9UpsDkiIPUSNGgCgYIKoZIzj0DAQehRANCAAST3v9ppIZFAHzL
+YO/qfytjfy/MBTp2PdtbHpEnTFfyV+DDH9NSVRHQ5CRESw8Ts7VZO4gfGJRKgQZ
rdafdzlD
-----END PRIVATE KEY-----